on:
  push:
    branches:
      - master





jobs:
  build:
    runs-on: ubuntu-latest
    

    steps:
      - uses: actions/checkout@v3
      - name: "Login to Docker Hub"
        run: docker login --username ${{ secrets.DOCKER_USERNAME1}} --password ${{ secrets.DOCKER_TOKEN1 }}

      - name: "Building Docker image "
        run: docker build -t ${{ secrets.DOCKER_USERNAME1}}/myimage .

      - name: "Pushintg to Docker "
        run: docker push ${{ secrets.DOCKER_USERNAME1}}/myimage 

      
      

       
      
      
      
