on:
  push:
    branches:
      - master





jobs:
  build:
    runs-on: ubuntu-latest
    

    steps:
      
  
      - name: 'BEROR'
        run: ls
      - uses: actions/checkout@v3
      - name: 'AFTER'
        run: ls

      

       
      
      
      
